import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import CardList from '../componentes/complex/allUse/CardList';
import ButtonList from '../componentes/complex/allUse/ButtonList';
import { assignActionsByStatus } from './generateActions';
import { DAYS, MONTHS } from '../constantes/DaysMonths';
import { CLASSBYSTATE } from '../constantes/CardObject';

export default function assignMonthElementType(
    acciones,
    type,
    sectionData,
    data
) {
    let structure = {};
    switch (type) {
        case "reservas":
            let resDate = new Date(data),
                tday = new Date(),
                cond = tday.getDate() === resDate.getDate() && tday.getMonth() === resDate.getMonth() && tday.getFullYear() === resDate.getFullYear();
            structure = sectionData !== null ? {
                title: {
                    data: resDate.getDate(),
                    class: cond ?
                        "content c-title highlight-title text-center" :
                        "content c-title text-center",
                },
                content: {},
                container: {
                    data: data,
                    class: "same-width text-center box-padding highlight-hover pointer fix-height blue-highlight-hover",
                    click: acciones ? acciones[0].click : null
                }
            } : {
                    title: {
                        data: resDate.getDate(),
                        class: "content c-title"
                    },
                    content: {},
                    container: {
                        class: "background-border same-width text-center box-padding fix-height",
                        data:data,
                        click: acciones ? acciones[0].click :  null
                    }
                };
            break;
        case "feriados":
            /**
             * actions: pass actions generated by generateActions functions
             * type: where is the function called from 
             * index: current index in data array
             * sectionData: data object from current object in loop
             */
            let date = new Date(data),
                today = new Date(),
                todayCond = today.getDate() === date.getDate() && today.getMonth() === date.getMonth() && today.getFullYear() === date.getFullYear();
            structure = sectionData !== null ? {
                title: {
                    data: date.getDate(),
                    class: todayCond ?
                        "content c-title highlight-title text-center" :
                        "content c-title text-center light-danger",
                },
                content: {
                    data: <ButtonList
                        displayList="flex-row nav-list no-padding"
                        container="align-center"
                        elemClass="box-transparent highlight-hover full-width text-left side-margin button-border border-box"
                        elems={acciones} />
                },
                container: {
                    class: todayCond ?
                        "same-width text-center box-padding highlight-title" :
                        "same-width text-center box-padding light-danger"
                }
            } : {
                    title: {
                        data: date.getDate(),
                        class: "content c-title"
                    },
                    content: {},
                    container: {
                        class: "background-border same-width text-center box-padding"
                    }
                };
            break;
    }
    return structure;
}




