export const validation = {
    id:{
        rules:{},
        fieldName:"Id"
    },
    eventos:{
        rules:{},
        fieldName:"Eventos"
    },
    descuento:{
        rules:{
            maxVal:100,
            minVal:0
        },
        fieldName:"Descuento"
    },
    descripcion:{
        rules:{
            maxLen:50
        },
        fieldName:"Descripción"
    },
    nombre:{
        rules:{
            maxLen:50,
            required:true
        },
        fieldName:"Nombre"
    },
};
export default validation;
