export const validation = {
    id:{
        rules:{},
        fieldName:"ID",
        casting:"integer"
    },
    id_usuario:{
        rules:{},
        fieldName:"ID del usuario",
        casting:"integer"
    },
    promociones:{
        rules:{},
        fieldName:"Promociones",
        casting:"array"
    },
    horarios:{
        rules:{
            required:true
        },
        fieldName:"Horarios",
        casting:"array"
    },
    feriados:{
        rules:{},
        fieldName:"Feriados",
        casting:"array"
    },
    descripcion:{
        rules:{
            maxLen:100,
            required:true
        },
        fieldName:"Descripción"
    },
    nombre:{
        rules:{
            maxLen:45,
            required:true
        },
        fieldName:"Nombre"
    },
    scope:{
        rules:{
            required:true
        },
        fieldName:"Estado",
        casting:"integer"
    }
};
export default validation;
